In [1]:
import numpy as np

In [3]:
b = np.array([[1, 3, 5],
              [2, 4, 8]], dtype=complex)
b

array([[1.+0.j, 3.+0.j, 5.+0.j],
       [2.+0.j, 4.+0.j, 8.+0.j]])

# Creating Arrays with Zeros

In [6]:
np.zeros((3, 4), dtype=int) * 15

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.pi

3.141592653589793

In [1]:
np.linspace()

NameError: name 'np' is not defined

In [2]:
2 + 2

4

In [3]:
50 - 5*6

20

In [4]:
(50 - 5*6) / 4

5.0

In [5]:
8 / 5 

1.6

In [14]:
17 % 3

5 * 3 + 2

17

In [10]:
5 ** 2
type()

25

In [11]:
2 ** 7

128

In [1]:
width = 20
height = 5 * 9
width * height

900

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [7]:
n

NameError: name 'n' is not defined

In [8]:
4 * 3.75 - 1

14.0

In [10]:
tax = 12.5 / 100
price = 100.50
price * tax

12.5625

In [11]:
price + _

113.0625

In [12]:
round(_, 2)

113.06

In [13]:
'spam eggs'

'spam eggs'

In [14]:
'doesn\'t'

"doesn't"

In [15]:
"doesn't"

"doesn't"

In [17]:
'"Yes," they said.'

'"Yes," they said.'

In [18]:
"\"Yes, \" they said"

'"Yes, " they said'

In [19]:
'"Isn\'t," they said.'

'"Isn\'t," they said.'

In [20]:
print('"Isn\'t," they said.')

"Isn't," they said.


In [22]:
s= 'First line. \nSecond line.'
s

'First line. \nSecond line.'

In [23]:
print(s)

First line. 
Second line.


In [24]:
print('C:\some\name')

C:\some
ame


In [26]:
print(r'C:\some\name')

C:\some\name


In [27]:
print('''\
Usage: thingy [OPTIONS]
    -h
    -H hostname
''')

Usage: thingy [OPTIONS]
    -h
    -H hostname



In [28]:
3 * 'un' + 'ium'

'unununium'

In [29]:
'Py' 'thon'

'Python'

In [35]:
text = ('Put several strings within parentheses ' 
       'to have them joined together.')
text

'Put several strings within parentheses to have them joined together.'

In [44]:
prefix = 'Py'
# prefix 'thon'

In [45]:
('un' * 3)'ium'

SyntaxError: invalid syntax (Temp/ipykernel_15384/1476873953.py, line 1)

In [46]:
prefix + 'thon'

'Python'

In [47]:
word = 'Python'
word[0]

'P'

In [48]:
word[5]

'n'

In [49]:
word[-1]

'n'

In [50]:
word[-2]

'o'

In [51]:
word[-6]

'P'

In [52]:
word[0:2]

'Py'

In [53]:
word[2:5]

'tho'

In [54]:
word[:2]

'Py'

In [55]:
word[4:]

'on'

In [56]:
word[-2:]

'on'

In [57]:
word[:2] + word[2:]

'Python'

In [58]:
word[42]

IndexError: string index out of range

In [59]:
word[4:42]

'on'

In [60]:
word[42:]

''

In [61]:
word[0] = 'J'

TypeError: 'str' object does not support item assignment

In [62]:
'J' + word[1:]

'Jython'

In [65]:
m = word[:2] + 'py'
m

'Pypy'

In [67]:
s = 'sjgejigengiengeigneign'
len(s)

22

In [68]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

In [69]:
squares[0]

1

In [70]:
squares[-1]

25

In [71]:
squares[-3:]

[9, 16, 25]

In [72]:
squares[:]

[1, 4, 9, 16, 25]

In [73]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [75]:
cubes = [1, 8, 27, 65, 125]
cubes[3] = 64
cubes

[1, 8, 27, 64, 125]

In [81]:
cubes.append(216)
cubes

[1, 8, 27, 64, 125, 216, 216]

In [84]:
cubes.remove(216)
cubes

[1, 8, 27, 64, 125]

In [86]:
cubes.append(7 ** 3)
cubes

[1, 8, 27, 64, 125, 343, 343]

In [87]:
cubes.remove(343)

In [88]:
cubes

[1, 8, 27, 64, 125, 343]

In [90]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [91]:
letters[2:5] = ['C', 'D', 'E']
letters

['a', 'b', 'C', 'D', 'E', 'f', 'g']

In [92]:
letters[2:5] = []

In [93]:
letters

['a', 'b', 'f', 'g']

In [94]:
letters[:] = []

In [95]:
letters

[]

In [96]:
letters = ['a', 'b', 'f', 'g']
len(letters)

4

In [97]:
a, b = 0, 1
while a < 10:
    print(a)
    a, b = b, a+b

0
1
1
2
3
5
8


In [98]:
c, d = 6, 7

In [99]:
c

6

In [104]:
a, b = 0, 1
while a < 1000:
    print(a, end=',')
    a, b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

In [108]:
x = int(input("Please enter an integer: "))

Please enter an integer:  42


In [109]:
if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

More


In [110]:
words = ['cat', 'window', 'defenestrate']

In [111]:
for w in words:
    print(w, len(w))

cat 3
window 6
defenestrate 12


In [112]:
for user, status in users.copy().items():
    if status == 'inactive':
        del users[user]

NameError: name 'users' is not defined

In [113]:
active_users = {}
for user, status in users.items():
    if status == 'active':
        active_users[user] = status

NameError: name 'user' is not defined

In [114]:
for i in range(5):
    print(i)


0
1
2
3
4


In [115]:
list(range(5, 10))

[5, 6, 7, 8, 9]

In [116]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [117]:
list(range(-10, -100, -30))

[-10, -40, -70]

In [118]:
a = ['Mary', 'had', 'a', 'little', 'lamb']

In [119]:
for i in range(len(a)):
    print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


In [120]:
range(10)

range(0, 10)

In [121]:
type(range(10))

range

In [122]:
sum(range(4))

6

In [134]:
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
            break
    else:
        print(n, 'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3


In [126]:
10 % 3

1

In [137]:
for num in range(2, 10):
    if num % 2 == 0:
        print("Found an even number", num)
        continue
    print("Found an odd number", num)

Found an even number 2
Found an odd number 3
Found an even number 4
Found an odd number 5
Found an even number 6
Found an odd number 7
Found an even number 8
Found an odd number 9
