In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize

4

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6, 7, 8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [13]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [16]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [17]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [20]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [21]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [22]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
from numpy import pi
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
x = np.linspace(0, 2 * pi, 5)
f = np.sin(x)

In [25]:
x

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [26]:
f

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [27]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [28]:
b = np.arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [31]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [32]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [33]:
c = a - b
c

array([20, 29, 38, 47])

In [34]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [35]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [36]:
a < 35

array([ True,  True, False, False])

In [37]:
A = np.array([[1, 1],
             [0, 1]])
B = np.array([[2, 0],
             [3, 4]])
A * B

array([[2, 0],
       [0, 4]])

In [38]:
A @ B

array([[5, 4],
       [3, 4]])

In [39]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [40]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [41]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [44]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [45]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [46]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [47]:
c.dtype.name

'float64'

In [48]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [49]:
d.dtype.name

'complex128'

In [50]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [51]:
a.sum()

3.1057109529998157

In [52]:
a.min()

0.027559113243068367

In [53]:
a.max()

0.8277025938204418

In [54]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [56]:
b.min(axis=1)

array([0, 4, 8])

In [57]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [58]:
B = np.arange(3)
B

array([0, 1, 2])

In [59]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [60]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [61]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [62]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [63]:
a[2]

8

In [64]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [65]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [66]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [67]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [68]:
1000**(1/3)

9.999999999999998

In [69]:
def f(x, y):
    return 10 * x + y

In [70]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [71]:
b[2, 3]

23

In [72]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [73]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [74]:
b[-1]

array([40, 41, 42, 43])

In [75]:
c = np.array([[[0, 1, 2],
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [76]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [77]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [78]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [79]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [80]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [81]:
a.shape

(3, 4)

In [82]:
a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [83]:
a.reshape(6, 2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [84]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [85]:
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [86]:
a.T.shape

(4, 3)

In [87]:
a.shape

(3, 4)

In [88]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [89]:
a.resize((2, 6))
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [90]:
a.reshape(3, -1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [91]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[9., 7.],
       [5., 2.]])

In [92]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[1., 9.],
       [5., 1.]])

In [93]:
np.vstack((a, b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [94]:
np.hstack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [95]:
from numpy import newaxis

In [96]:
np.column_stack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [97]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [98]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [99]:
a[:, newaxis]

array([[4.],
       [2.]])

In [100]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [101]:
np.column_stack is np.hstack

False

In [102]:
np.row_stack is np.vstack

True

In [103]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

In [104]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

In [105]:
np.hsplit(a, 3)

[array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]]),
 array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]),
 array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]])]

In [106]:
np.hsplit(a, (3, 4))

[array([[6., 7., 6.],
        [8., 5., 5.]]),
 array([[9.],
        [7.]]),
 array([[0., 5., 4., 0., 6., 8., 5., 2.],
        [1., 8., 6., 7., 1., 8., 1., 0.]])]

In [107]:
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
b = a
b is a

True

In [108]:
def f(x):
    print(id(x))

In [109]:
id(a)

1465667237232

In [110]:
f(a)

1465667237232


In [111]:
c = a.view()
c is a

False

In [112]:
c.base is a

True

In [113]:
c.flags.owndata

False

In [114]:
c = c.reshape((2, 6))

In [115]:
a.shape

(3, 4)

In [116]:
c[0, 4] = 1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [117]:
s = a[:, 1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [118]:
d = a.copy()
d is a

False

In [119]:
d.base is a

False

In [120]:
d[0, 0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [121]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a

In [122]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [123]:
a = np.arange(12)**2
i = np.array([1, 1, 3, 8, 5])
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [124]:
j = np.array([[3, 4], [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [129]:
palette = np.array([[0, 0, 0],
                   [255, 0, 0],
                   [0, 255, 0],
                   [0, 0, 355],
                   [255, 255, 255]])

In [130]:
image = np.array([[0, 1, 2, 0],
                  [0, 3, 4, 0]])

In [131]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 355],
        [255, 255, 255],
        [  0,   0,   0]]])

In [132]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
i = np.array([[0, 1],
              [1, 2]])
j = np.array([[2, 1],
              [3, 3]])

In [134]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [136]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [137]:
l = (i, j)
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [138]:
s = np.array([i, j])
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [139]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [140]:
time = np.linspace(20, 145, 5)
data = np.sin(np.arange(20)).reshape(5, 4)
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [141]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [142]:
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1], dtype=int64)

In [149]:
time_max = time[ind]

In [150]:
data_max = data[ind, range(data.shape[1])]

In [151]:
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [146]:
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [147]:
np.all(data_max == data.max(axis=0))

True

In [156]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [157]:
a[[1, 3, 4]] = 0
a

array([0, 0, 2, 0, 0])

In [158]:
a = np.arange(5)
a[[0, 0, 2]] = [1, 2, 3]
a

array([2, 1, 3, 3, 4])

In [159]:
a = np.arange(5)
a[[0, 0, 2]] += 1
a

array([1, 1, 3, 3, 4])